### ISSUE TITLE
Callback not called on opted-out state updates

### ISSUE THREAD

**Issue by thoughtspile** [the-road-to-learn-react/use-state-with-callback#26]
When a state update is called with the current value and optimized away, the callback is never called (with any method). This at least deserves a mention in the readme as a _notable difference_ or a _pitfall_.

Expected behavior: The callback is always called, just like with the class components.

repro: https://codesandbox.io/s/thirsty-frog-h8c63?file=/src/App.js

**Comment by edub008** [comment]
I am also experiencing this issue, when called with the current value (and in my case possibly also when trying to update a nested state value with a different type of object, though haven't verified that yet) the callback of this module is not called. 

For now I am looping through my state changes to make sure there are differences (basically performing the optimization pass manually instead of letting react handle) and if none detected handle the callback myself, however would be great if this was fixed soon please.

**Comment by rwieruch** [comment]
Thanks. I mentioned it over here: https://github.com/the-road-to-learn-react/use-state-with-callback/commit/273d4f288b94c4dd1646d3546d6bf33824aa0605 

I think it's the preferred way for developers getting the final result, no?
